# Generated by Django 3.0.6 on 2020-05-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20200529_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_private',
            field=models.BooleanField(default=False),
        ),
    ]
